config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    common: [release]
    client-java: [release]
    client-python: [release]
    client-nodejs: [release]

build:
  quality:
    filter:
      owner: graknlabs
      branch: master
    dependency-analysis:
      image: graknlabs-ubuntu-20.04-java11
      script: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel build //...
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
    test-query-graql-lang:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel test //test/query:graql-lang --test_output=errors
    test-query-graql-java:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel test //test/query:graql-java --test_output=errors
    test-example-java:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel run //:grakn-extractor -- dist/grakn-core-all-linux
        nohup ./dist/grakn-core-all-linux/grakn server start
        bazel test //test/example/java:phone-calls --test_output=errors
        bazel test //test/example/java:social-network --test_output=errors
    test-example-nodejs:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel run //:grakn-extractor -- dist/grakn-core-all-linux
        nohup ./dist/grakn-core-all-linux/grakn server start
        bazel test //test/example/nodejs:phone-calls --test_output=errors
        bazel test //test/example/nodejs:social-network --test_output=errors
    test-example-python:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        pyenv global system
        bazel run //:grakn-extractor -- dist/grakn-core-all-linux
        nohup ./dist/grakn-core-all-linux/grakn server start
        bazel test //test/example/python:phone-calls --test_output=errors
        bazel test //test/example/python:social-network --test_output=errors
    test-links:
      image: graknlabs-ubuntu-20.04
      type: foreground
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel test //test/links:test --test_output=errors
    release-staging:
      filter:
        owner: graknlabs
        branch: development
      image: graknlabs-ubuntu-20.04
      type: foreground
      dependencies: [build, test-query-graql-lang, test-query-graql-java, test-example-java, test-example-nodejs, test-example-python, test-links]
      script: |
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:docs -- development $CIRCLE_SHA1
    
  execution:
    - build
    - test-query-graql-lang
    - test-query-graql-java
    - test-example-java
    - test-example-nodejs
    - test-example-python
    - test-links
    - release-staging


release:
  filter:
    owner: graknlabs
    branch: master
  validation:
    validate-dummy:
      image: graknlabs-ubuntu-20.04
      script: |
        echo dummy
  deployment:
    deploy-github:
      image: graknlabs-ubuntu-20.04
      script: |
        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
        export ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
        export ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run @graknlabs_dependencies//distribution/artifact:create-netrc
        bazel run @graknlabs_dependencies//tool/release:docs -- master $CIRCLE_SHA1
